### ISSUE TITLE
Replace Makefile with scripts

### ISSUE THREAD

**Issue by marcosschroh** [kpn/kstreams#12]
**Is your feature request related to a problem? Please describe.**
We want to replace the functionality of the `Makefile` with individual scripts so we have one center place where all the `administrative` tasks are located and we can follow the [Scripts to Rule Them All](https://github.blog/2015-06-30-scripts-to-rule-them-all/)

**Describe the solution you'd like**
```bash
scripts
└── cluster/
    ├── bash
    ├── logs
    ├── restart
    ├── start
    ├── stop
    └── topics/
        ├── create
        └── ls
```

**Comment by marcosschroh** [comment]
Let's also add the `send-event` script. Something like:

```bash
docker-compose exec kafka kafka-console-producer --broker-list kafka:9092 --topic $1

**Comment by Woile** [comment]
```
events/send
events/read
```
