### ISSUE TITLE
Enum encoded wrong in SASL handshake

### ISSUE THREAD

**Issue by jurrian** [kpn/kstreams#130]
**Describe the bug**
I broke my head why kstreams would not connect to Confluent Cloud with SASL_SSL in PLAIN mode. I found that the message bytes being sent to Confluent in handshake is this: ```b'\x00\x11\x00\x00\x00\x00\x00\x01\x00\x13aiokafka-producer-1\x00\x13SaslMechanism.PLAIN'```, note that Confluent expects "PLAIN" instead of "SaslMechanism.PLAIN". Confluent then returns it cannot do the handshake since it does not match its enabled_mechanisms.

**To Reproduce**
Current situation:
```
class SaslMechanism(str, Enum):
    PLAIN = "PLAIN"
    GSSAPI = "GSSAPI"
    SCRAM_SHA_256 = "SCRAM-SHA-256"
    SCRAM_SHA_512 = "SCRAM-SHA-512"
    OAUTHBEARER = "OAUTHBEARER"

str(Kafka(sasl_mechanism='PLAIN').sasl_mechanism) == 'PLAIN'  # Evaluates False
```

**Expected behavior**
Using StrEnum:
```
class SaslMechanism(StrEnum):
    PLAIN = "PLAIN"
    GSSAPI = "GSSAPI"
    SCRAM_SHA_256 = "SCRAM-SHA-256"
    SCRAM_SHA_512 = "SCRAM-SHA-512"
    OAUTHBEARER = "OAUTHBEARER"

str(Kafka(sasl_mechanism='PLAIN').sasl_mechanism) == 'PLAIN'  # Evaluates True
```

I confirmed that this does establish the connection.

**Additional context**
The solution here is to use `StrEnum` instead, however this was only introduced in 3.11. Python 3.6+ can install it `pip install StrEnum`. If there is support needed for older versions then I would advise implement `def __str__(self): return str(self.value)` on the enum classes. The problem probably also applies to SecurityProtocol.

**Comment by marcosschroh** [comment]
Thanks @jurrian for reporting this bug. We will try to fix it asap!
