### ISSUE TITLE
Document StreamEngine API

### ISSUE THREAD

**Issue by marcosschroh** [kpn/kstreams#14]
**Is your feature request related to a problem? Please describe.**
We want to document/describe the `StreamEngine` API.

**Describe the solution you'd like**
Use the library [mkautodoc](https://github.com/tomchristie/mkautodoc) so with `dosctrings` we can describe in an easy way the API. 

Code example [python-schema-registry-client](https://github.com/marcosschroh/python-schema-registry-client/blob/master/schema_registry/client/client.py#L39)

Result: https://marcosschroh.github.io/python-schema-registry-client/client/#schemaregistryclient

**Comment by Woile** [comment]
I would also consider https://timothycrosley.github.io/pdocs/ instead of mkautodoc

**Comment by Woile** [comment]
After much research, I think we should go for https://github.com/mkdocstrings/mkdocstrings seems that `mkautodoc` is not maintained.
