### ISSUE TITLE
UDF middleware cannot handle ConsumerRecord with specified generic typing

### ISSUE THREAD

**Issue by JeroennC** [kpn/kstreams#226]
**Describe the bug**

When specifying the generic types in ConsumerRecord, e.g. `ConsumerRecord[Any, Any]` in the stream function signature, the `ANNOTATIONS_TO_PARAMS` mapping fails to map the consumerrecord to the parameter.

https://github.com/kpn/kstreams/blob/5e85da3c9a7819089acbdc91405ca3ff1f4e30e5/kstreams/middleware/udf_middleware.py#L28

**To Reproduce**
Create a UDF style stream function with `cr: ConsumerRecord[Any, Any]`

**Expected behavior**
It should just work like it does without specifying the generics.

**Comment by woile** [comment]
Thanks for reporting, we are gonna investigate 👁️ , it might be fixed with the new DI pr #58 but it's still a bit away
