### ISSUE TITLE
Add a simple `run` to the `StreamEngine`

### ISSUE THREAD

**Issue by Woile** [kpn/kstreams#45]
## Goal
Make it easier to use and remove dependencies

## Description
At the moment it is a bit hard to run forever without something like `aiorun`. To solve that, we can add a small `run` function in the `StreamEngine`.

For the end user the interface should look something like this:

```python
import asyncio
from kstreams import create_engine, Stream


stream_engine = create_engine(title="my-stream-engine")

@stream_engine.stream("local--kstream")
async def consume(stream: Stream):
    async for cr in stream:
        print(f"Event consumed: headers: {cr.headers}, payload: {cr.value}")

asyncio.run(stream_engine.run())
```

## Sketch 

A very rough implementation of `run`:

```py
async def run(self):
    loop = asyncio.get_event_loop()
    await self.start()
    try:
        loop.run_forever()
    except:
        await self.stop()
```

**Comment by marcosschroh** [comment]
closed by https://github.com/kpn/kstreams/pull/50
